#------------------------------------------------------------------#
# Target system 						   #
#------------------------------------------------------------------#
#SYSTEM =	"erebos"
SYSTEM =	"Laptop"

#------------------------------------------------------------------#
# DEFINEFLAGS                                                      #
#------------------------------------------------------------------#
#DEFINEFLAGS	=	-DGADGET 
#DEFINEFLAGS    =	-DAHFptfocus=0 
#DEFINEFLAGS	=	-DSUSSING2013
#DEFINEFLAGS	+=	-DMULTIMASS
#DEFINEFLAGS	+=	-DGAS_PARTICLES

#------------------------------------------------------------------#
# Set environment for the system                                   #
#------------------------------------------------------------------#
ifeq ($(SYSTEM), "Laptop")
	CC         	=	mpicc
	CCFLAGS		= 	-std=c99 -Wall -W -fopenmp -lm
	FC         	=	mpif90
	OPTIMIZE	=	-O2
	MPILIBS		= 	-lmpi
	LNFLAGS		=	-lm -lz
	DEFINEFLAGS	+=	-DWITH_MPI
	MAKE		=	make
endif

ifeq ($(SYSTEM), "erebos")
	CC         	=	/z/carlesi/libs/bin/mpicc
	CCFLAGS		= 	-std=c99 -Wall -W -fopenmp
	FC         	=	mpif90
	OPTIMIZE	=	-O2
	MPILIBS		= 	/z/carlesi/libs/lib
	MPIINCL		= 	/z/carlesi/libs/include
	LNFLAGS		=	-lm -lz
	LOCLIBS		= 	-L${MPILIBS}
	LOCINCL		= 	-I${MPIINCL}
	CCFLAGS		+=	${LOCINCL} ${LOCLIBS}
	DEFINEFLAGS	+=	-DWITH_MPI
	MAKE		=	make
endif
