#******************************************************************#
# Sample Makefile.config.  Be sure to edit this to your likings    #
# and copy it to Makefile.config.                                  #
#******************************************************************#

#------------------------------------------------------------------#
# Select the target system                                         #
# (define your own, if needed!)                                    #
#------------------------------------------------------------------#
#SYSTEM =	"Standard SQL"
#SYSTEM =	"Standard OpenMP"
#SYSTEM =	"Standard MPI"
#SYSTEM =	"Standard MPI+OpenMP"
#SYSTEM =	"erebos"
SYSTEM =	"Laptop"
#SYSTEM =	"SuperMUC"
#SYSTEM =	"Debug"

#------------------------------------------------------------------#
# DEFINEFLAGS                                                      #
#------------------------------------------------------------------#
#DEFINEFLAGS	=	-DGADGET 
#DEFINEFLAGS    =	-DAHFptfocus=0 
#DEFINEFLAGS	=	-DSUSSING2013
#DEFINEFLAGS	+=	-DMULTIMASS
#DEFINEFLAGS	+=	-DGAS_PARTICLES



#------------------------------------------------------------------#
# Set environment for the system                                   #
#------------------------------------------------------------------#
ifeq ($(SYSTEM), "Laptop")
	CC         	=	mpicc
	CCFLAGS		= 	-std=c99 -Wall -W -fopenmp -lm
	FC         	=	mpif90
	OPTIMIZE	=	-O2
	MPILIBS		= 	-lmpi
	LNFLAGS		=	-lm -lz
	DEFINEFLAGS	+=	-DWITH_MPI
	MAKE		=	make
endif


ifeq ($(SYSTEM), "erebos")
	CC         	=	/z/carlesi/libs/bin/mpicc
	CCFLAGS		= 	-std=c99 -Wall -W -fopenmp
	FC         	=	mpif90
	OPTIMIZE	=	-O2
	MPILIBS		= 	/z/carlesi/libs/lib
	MPIINCL		= 	/z/carlesi/libs/include
	LNFLAGS		=	-lm -lz
	LOCLIBS		= 	-L${MPILIBS}
	LOCINCL		= 	-I${MPIINCL}
	CCFLAGS		+=	${LOCINCL} ${LOCLIBS}
	DEFINEFLAGS	+=	-DWITH_MPI
	MAKE		=	make
endif

ifeq ($(SYSTEM), "Standard MPI")
	CC         	=	mpicc -std=c99 -Wall -W -fopenmp
	FC         	=	mpif90
	OPTIMIZE	=	-O2
	CCFLAGS		=
	LNFLAGS		=
	DEFINEFLAGS	+=	-DWITH_MPI
	MAKE		=	make
endif


ifeq ($(SYSTEM), "Standard MPI+OpenMP")
	CC         	=	mpicc -std=c99 -Wall -W -fopenmp
	FC         	=	g77
	OPTIMIZE	=	-O2
	CCFLAGS		=
	LNFLAGS		=
	DEFINEFLAGS	+=	-DWITH_MPI -DWITH_OPENMP
	DEFINEFLAGS	+=	-DGENERATE_TREE_LOG
	DEFINEFLAGS	+=	-DPATCH_THREADS_LOG
	DEFINEFLAGS	+=	-DREVIEW_SUBCUBES_FORMATION
		MAKE		=	make
endif
